# <span style="color:#0f766e; font-weight:700;">Analiza Danych (Python) - Lekcja 3</span>

1. [Czym jest DataFrame?](#1.-Czym-jest-DataFrame?)
2. [Najważniejsze operacje na DataFrame](#2.-Najważniejsze-operacje-na-DataFrame)
3. [Dane do ćwiczeń](#3.-Dane-do-ćwiczeń)
4. [Zadania](#4.-Zadania)
5. [Najczęstsze błędy](#Najczęstsze-błędy)

# <span style="color:#0f766e; font-weight:700;">1. Czym jest DataFrame?</span>

`DataFrame` to podstawowa struktura danych w `pandas`.

Najprościej:
- jest to **tabela** z wierszami i kolumnami,
- każda kolumna ma nazwę,
- każda kolumna ma typ danych (`dtype`),
- można na niej wykonywać filtrowanie, agregacje, łączenie tabel i przekształcenia.

W praktyce `DataFrame` łączy w sobie cechy:
- arkusza kalkulacyjnego,
- tabeli SQL,
- obiektu programistycznego, na którym można budować cały pipeline analityczny.

## <span style="color:#0f766e; font-weight:700;">Jak myśleć o DataFrame?</span>

- **wiersz** = jedna obserwacja / rekord,
- **kolumna** = jedna zmienna / cecha,
- **indeks** = etykieta wiersza,
- **dtype** = techniczna reprezentacja danych w pamięci.

Przykłady:
- tabela pracowników,
- tabela transakcji,
- wyniki ankiety,
- logi eksperymentu.

# <span style="color:#0f766e; font-weight:700;">2. Najważniejsze operacje na DataFrame</span>

## <span style="color:#0f766e; font-weight:700;">Tworzenie i wczytywanie</span>

Najczęściej używane wejścia:
- `pd.read_csv()` - wczytuje dane z pliku CSV do `DataFrame`.
- `pd.read_excel()` - wczytuje dane z pliku Excel (`.xlsx`, `.xls`).
- `pd.read_json()` - wczytuje dane zapisane w formacie JSON.
- `pd.DataFrame()` - tworzy `DataFrame` ręcznie, np. ze słownika lub listy.

Szybka diagnostyka po wczytaniu:
- `head()` - pokazuje pierwsze wiersze tabeli.
- `tail()` - pokazuje ostatnie wiersze tabeli.
- `sample()` - losuje przykładowe rekordy do szybkiego podglądu.
- `shape` - zwraca liczbę wierszy i kolumn.
- `info()` - pokazuje typy kolumn, braki danych i podstawową strukturę.
- `dtypes` - zwraca typ danych każdej kolumny.
- `describe()` - liczy podstawowe statystyki opisowe dla kolumn liczbowych.

Przykład:
```python
import pandas as pd

df = pd.read_csv('plik.csv')
df.head()
df.info()
```

## <span style="color:#0f766e; font-weight:700;">Wybieranie danych</span>

Najważniejsze narzędzia:
- wybór kolumn: `df[['kol1', 'kol2']]` - zwraca nowy `DataFrame` z wybranymi kolumnami.
- wybór jednej kolumny: `df['kol1']` - zwraca pojedynczą serię (`Series`).
- wybór etykietami: `df.loc[...]` - wybiera dane po nazwach wierszy i kolumn.
- wybór po pozycjach: `df.iloc[...]` - wybiera dane po numerach pozycji.
- filtrowanie logiczne: `df[df['wiek'] > 30]` - zostawia tylko rekordy spełniające warunek.
- zapytania tekstowe: `df.query(...)` - pozwala filtrować dane składnią podobną do SQL.

Przykład:
```python
df.loc[df['salary_pln'] > 10000, ['department', 'salary_pln']]
```

## <span style="color:#0f766e; font-weight:700;">Czyszczenie i transformacje</span>

Najważniejsze metody:
- `rename()` - zmienia nazwy kolumn lub indeksu.
- `drop()` - usuwa wskazane kolumny albo wiersze.
- `dropna()` - usuwa wiersze lub kolumny z brakami danych.
- `fillna()` - uzupełnia braki danych wskazaną wartością.
- `astype()` - konwertuje kolumnę na inny typ danych.
- `assign()` - dodaje nową kolumnę lub kilka kolumn w jednym kroku.
- `replace()` - zamienia wskazane wartości na inne.
- `sort_values()` - sortuje dane według wartości w kolumnie.
- `sort_index()` - sortuje dane według indeksu.
- `reset_index()` - przywraca zwykły indeks liczbowy.
- `set_index()` - ustawia wybraną kolumnę jako indeks.

Przykład:
```python
df = df.rename(columns={'salary_pln': 'salary'})
df = df.sort_values('salary', ascending=False)
```

## <span style="color:#0f766e; font-weight:700;">Agregacje i grupowanie</span>

Najważniejsze:
- `value_counts()` - liczy częstość występowania wartości w kolumnie.
- `groupby()` - dzieli dane na grupy według jednej lub kilku kolumn.
- `agg()` - pozwala policzyć kilka agregacji naraz.
- `mean()` - liczy średnią.
- `median()` - liczy medianę.
- `sum()` - liczy sumę.
- `min()` - zwraca wartość minimalną.
- `max()` - zwraca wartość maksymalną.
- `std()` - liczy odchylenie standardowe.
- `nunique()` - liczy liczbę unikalnych wartości.

Przykład:
```python
df.groupby('department').agg(
    salary_mean=('salary_pln', 'mean'),
    people=('employee_id', 'count')
)
```

## <span style="color:#0f766e; font-weight:700;">Łączenie tabel</span>

Najważniejsze:
- `merge()` - łączy dwie tabele po wspólnym kluczu.
- `join()` - wygodne łączenie po indeksie lub kluczach.
- `concat()` - skleja tabele pionowo albo poziomo.

Przykład:
```python
df = employees.merge(departments, on='department', how='left')
```

## <span style="color:#0f766e; font-weight:700;">Zmiana kształtu tabeli</span>

Najważniejsze:
- `pivot_table()` - tworzy tabelę przestawną z agregacją.
- `pivot()` - przekształca układ danych bez agregowania.
- `melt()` - zamienia układ szeroki na długi.

Przykład:
```python
scores_long = scores.melt(
    id_vars='employee_id',
    var_name='quarter',
    value_name='score'
)
```

## <span style="color:#0f766e; font-weight:700;">Operacje tekstowe i daty</span>

Bardzo ważne accesory:
- `.str` - udostępnia metody do pracy na tekście w kolumnach.
- `.dt` - udostępnia metody do pracy na datach i czasie.

Najczęściej używane:
- `str.lower()` - zamienia tekst na małe litery.
- `str.strip()` - usuwa zbędne spacje z początku i końca tekstu.
- `str.contains()` - sprawdza, czy tekst zawiera wzorzec.
- `to_datetime()` - konwertuje tekst na datę.
- `dt.year` - wyciąga rok z daty.
- `dt.month` - wyciąga numer miesiąca.
- `dt.day_name()` - zwraca nazwę dnia tygodnia.

Przykład:
```python
df['hire_date'] = pd.to_datetime(df['hire_date'])
df['year'] = df['hire_date'].dt.year
```

## <span style="color:#0f766e; font-weight:700;">Wykonywalne przykłady</span>

Poniżej znajdziesz przykłady kodu dla każdej najważniejszej grupy operacji na `DataFrame`. Każdą komórkę można uruchomić niezależnie.

## <span style="color:#0f766e; font-weight:700;">Przykład 1: Wczytywanie i szybka diagnostyka</span>

Ta komórka pokazuje, jak wczytać dane i natychmiast sprawdzić ich strukturę: `head`, `tail`, `sample`, `shape`, `info`, `dtypes`, `describe`.

In [1]:
import pandas as pd

# Wczytujemy plik CSV do obiektu DataFrame.
# Parametr: ścieżka tekstowa 'dane_lekcja3/employees.csv' wskazuje plik źródłowy.
df = pd.read_csv('dane_lekcja3/employees.csv')

# head() pokazuje pierwsze 5 wierszy.
# Brak parametru oznacza domyślnie n=5.
print('HEAD:')
print(df.head())
print()

# tail() pokazuje ostatnie 5 wierszy.
# Brak parametru oznacza domyślnie n=5.
print('TAIL:')
print(df.tail())
print()

# sample() losuje przykładowe rekordy.
# Parametr 3 oznacza liczbę losowanych wierszy.
# Parametr random_state=42 ustawia ziarno losowości, więc wynik będzie powtarzalny.
print('SAMPLE (3):')
print(df.sample(3, random_state=42))
print()

# shape nie jest funkcją, tylko atrybutem.
# Zwraca krotkę: (liczba_wierszy, liczba_kolumn).
print('SHAPE:', df.shape)
print()

# info() pokazuje strukturę tabeli.
# Widzimy liczbę niepustych wartości, typy danych i przybliżone zużycie pamięci.
print('INFO:')
df.info()
print()

# dtypes zwraca serię z typami każdej kolumny.
print('DTYPES:')
print(df.dtypes)
print()

# describe() liczy statystyki opisowe.
# Parametr include='all' każe uwzględnić także kolumny tekstowe.
# .T transponuje wynik, żeby łatwiej czytać statystyki dla każdej kolumny w wierszu.
# head(10) ogranicza wydruk do pierwszych 10 wierszy wyniku.
print('DESCRIBE:')
print(df.describe(include='all').T.head(10))

HEAD:
   employee_id first_name  last_name department     city  age  salary_pln  \
0            1     Szymon  Zielinski      sales  Wroclaw   31    12928.65
1            2      Marta   Kowalski         hr   Krakow   25     9648.33
2            3        Iga  Kaczmarek         hr   Poznan   23    10907.36
3            4    Roksana      Mazur        ops  Wroclaw   55    10229.72
4            5     Celina  Kaczmarek  analytics   Poznan   57     8448.04

   bonus_pct  performance_score  projects_count  remote_days   hire_date  \
0      0.076               4.23               9            1  2021-02-09
1      0.068               3.28               8           13  2024-10-02
2      0.166               2.76               4           13  2020-05-17
3      0.011               3.06               8            0  2023-05-31
4      0.163               2.60               1            5  2024-05-26

   is_manager contract_type
0           0      Zlecenie
1           0           UoP
2           1           UoP
3           1           UoP
4           0           UoP

TAIL:
     employee_id first_name  last_name department      city  age  salary_pln  \
695          696     Alicja      Mazur         hr    Gdansk   55     9535.34
696          697     Szymon  Grabowska        ops  Warszawa   43    11872.27
697          698   Gabriela     Wojcik  analytics      Lodz   48    10737.17
698          699   Wiktoria     Wojcik   research    Poznan   35     9374.70
699          700   Gabriela      Nowak        ops      Lodz   45    10515.37

     bonus_pct  performance_score  projects_count  remote_days   hire_date  \
695      0.039               2.25               2            0  2018-10-17
696      0.164               4.39              10            3  2018-08-19
697      0.228               3.61               7            4  2018-08-20
698      0.194               3.39              11           19  2024-03-11
699      0.064               2.45               5           18  2022-07-16

     is_manager contract_type
695           0      Zlecenie
696           1           B2B
697           0           B2B
698           0           UoP
699           0           UoP

SAMPLE (3):
     employee_id first_name   last_name department    city  age  salary_pln  \
158          159     Tomasz    Krawczyk    product    Lodz   37    13087.14
500          501    Roksana  Piotrowski   research  Krakow   24     9176.85
396          397     Patryk      Wojcik         it  Lublin   24    13349.23

     bonus_pct  performance_score  projects_count  remote_days   hire_date  \
158      0.230               4.73               6           11  2024-04-05
500      0.046               2.26               9           16  2021-08-01
396      0.101               3.09               6            8  2019-01-18

     is_manager contract_type
158           0           B2B
500           0           UoP
396           1           UoP

SHAPE: (700, 14)

INFO:
<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        700 non-null    int64
 1   first_name         700 non-null    str
 2   last_name          700 non-null    str
 3   department         700 non-null    str
 4   city               700 non-null    str
 5   age                700 non-null    int64
 6   salary_pln         700 non-null    float64
 7   bonus_pct          700 non-null    float64
 8   performance_score  700 non-null    float64
 9   projects_count     700 non-null    int64
 10  remote_days        700 non-null    int64
 11  hire_date          700 non-null    str
 12  is_manager         700 non-null    int64
 13  contract_type      700 non-null    str
dtypes: float64(3), int64(5), str(6)
memory usage: 76.7 KB

DTYPES:
employee_id            int64
first_name               str
last_name                str
department               str
city                     str
age                    int64
salary_pln           float64
bonus_pct            float64
performance_score    float64
projects_count         int64
remote_days            int64
hire_date                str
is_manager             int64
contract_type            str
dtype: object

DESCRIBE:
                   count unique       top freq          mean         std  \
employee_id        700.0    NaN       NaN  NaN         350.5   202.21688
first_name           700     20    Tomasz   44           NaN         NaN
last_name            700     10    Wojcik   89           NaN         NaN
department           700      8  research  106           NaN         NaN
city                 700      8      Lodz  108           NaN         NaN
age                700.0    NaN       NaN  NaN     40.137143   11.067541
salary_pln         700.0    NaN       NaN  NaN  11459.368657  2318.97145
bonus_pct          700.0    NaN       NaN  NaN       0.12885    0.072209
performance_score  700.0    NaN       NaN  NaN      3.415414    0.876955
projects_count     700.0    NaN       NaN  NaN      6.164286    3.165919

                       min        25%        50%         75%       max
employee_id            1.0     175.75      350.5      525.25     700.0
first_name             NaN        NaN        NaN         NaN       NaN
last_name              NaN        NaN        NaN         NaN       NaN
department             NaN        NaN        NaN         NaN       NaN
city                   NaN        NaN        NaN         NaN       NaN
age                   22.0       30.0       40.0        50.0      58.0
salary_pln         4954.65  9789.1425  11469.375  12988.9975  20476.39
bonus_pct              0.0    0.06575     0.1315        0.19      0.25
performance_score      2.0       2.59       3.38        4.16      4.99
projects_count         1.0       3.75        6.0         9.0      11.0

## <span style="color:#0f766e; font-weight:700;">Przykład 2: Wybieranie kolumn, filtrowanie, `loc`, `iloc`, `query`</span>

Ta komórka pokazuje różnicę między wyborem kolumn, filtrowaniem warunkiem, wyborem po etykietach (`loc`) i po pozycjach (`iloc`).

In [ ]:
import pandas as pd

# Wczytujemy dane pracowników do DataFrame.
df = pd.read_csv('dane_lekcja3/employees.csv')

# Wybór kilku kolumn przez listę nazw.
# Podwójne nawiasy kwadratowe zwracają DataFrame, a nie pojedynczą serię.
subset = df[['employee_id', 'department', 'city', 'salary_pln']]
print('WYBRANE KOLUMNY:')
print(subset.head())
print()

# Filtrowanie logiczne.
# Warunek df['salary_pln'] > 12000 tworzy serię wartości True/False.
# DataFrame[warunek] zostawia tylko wiersze, dla których warunek jest True.
high_salary = df[df['salary_pln'] > 12000]
print('PENSJA > 12000:')
print(high_salary[['employee_id', 'department', 'salary_pln']].head())
print()

# loc wybiera dane po etykietach.
# Pierwszy argument 0:4 oznacza zakres wierszy po indeksie.
# Drugi argument to lista nazw kolumn, które chcemy pokazać.
print('LOC (wiersze 0:4, konkretne kolumny):')
print(df.loc[0:4, ['first_name', 'last_name', 'salary_pln']])
print()

# iloc wybiera dane po pozycjach liczbowych.
# Pierwszy argument 0:5 oznacza wiersze o pozycjach 0-4.
# Drugi argument 1:4 oznacza kolumny o pozycjach 1-3.
print('ILOC (wiersze 0:5, kolumny 1:4):')
print(df.iloc[0:5, 1:4])
print()

# query() pozwala zapisać filtr jako czytelny tekst.
# Wewnątrz stringa odwołujemy się do nazw kolumn bez df['...'].
# Wynik dodatkowo ograniczamy do kilku kolumn.
print('QUERY department == analytics and salary_pln > 10000:')
print(
    df.query("department == 'analytics' and salary_pln > 10000")
      [['employee_id', 'department', 'salary_pln']]
      .head()
)

## <span style="color:#0f766e; font-weight:700;">Przykład 3: Transformacje, zmiana nazw, nowe kolumny, sortowanie, indeks</span>

Ta komórka pokazuje typowy pipeline przekształceń na `DataFrame`.

In [ ]:
import pandas as pd

# Wczytujemy dane pracowników.
df = pd.read_csv('dane_lekcja3/employees.csv')

# rename() zmienia nazwy kolumn.
# Parametr columns przyjmuje słownik: stara_nazwa -> nowa_nazwa.
df = df.rename(columns={'salary_pln': 'salary'})

# assign() dodaje nowe kolumny w jednym kroku.
# annual_salary to pensja miesięczna * 12.
# bonus_value to liczbowy odpowiednik procentowego bonusu.
df = df.assign(
    annual_salary=df['salary'] * 12,
    bonus_value=df['salary'] * df['bonus_pct']
)

# replace() podmienia wskazane wartości.
# Tutaj zamieniamy skrót 'UoP' na pełniejszą nazwę.
# Parametr przekazujemy jako słownik: stara_wartość -> nowa_wartość.
df['contract_type'] = df['contract_type'].replace({'UoP': 'umowa_o_prace'})

# sort_values() sortuje tabelę po wartości w kolumnie.
# Parametr 'annual_salary' wskazuje kolumnę sortowania.
# Parametr ascending=False ustawia sortowanie malejące.
sorted_df = df.sort_values('annual_salary', ascending=False)
print('PO SORTOWANIU:')
print(sorted_df[['employee_id', 'salary', 'annual_salary']].head())
print()

# set_index() ustawia wskazaną kolumnę jako indeks wierszy.
# Parametr 'employee_id' mówi, która kolumna ma stać się indeksem.
indexed = sorted_df.set_index('employee_id')
print('PO SET_INDEX:')
print(indexed.head(3))
print()

# reset_index() przywraca zwykły indeks liczbowy i zwraca dawny indeks jako kolumnę.
reset_back = indexed.reset_index()
print('PO RESET_INDEX:')
print(reset_back.head(3))

## <span style="color:#0f766e; font-weight:700;">Przykład 4: `value_counts`, `groupby`, `agg`, `nunique`</span>

Ta komórka pokazuje najczęstsze operacje podsumowujące na `DataFrame`.

In [ ]:
import pandas as pd

# Wczytujemy tabelę pracowników.
df = pd.read_csv('dane_lekcja3/employees.csv')

# value_counts() liczy wystąpienia każdej wartości w kolumnie.
print('LICZEBNOSC DEPARTAMENTOW:')
print(df['department'].value_counts())
print()

# nunique() liczy liczbę unikalnych wartości w kolumnie.
print('LICZBA UNIKALNYCH MIAST:', df['city'].nunique())
print()

# groupby('department') dzieli dane na grupy według działu.
# agg() liczy wiele agregacji jednocześnie.
# Każdy wpis ma postać: nowa_nazwa_kolumny=(kolumna_wejściowa, funkcja_agregująca).
summary = df.groupby('department').agg(
    employees=('employee_id', 'count'),
    salary_mean=('salary_pln', 'mean'),
    salary_median=('salary_pln', 'median'),
    performance_mean=('performance_score', 'mean')
)

# sort_values() porządkuje wynik po średniej pensji malejąco.
summary = summary.sort_values('salary_mean', ascending=False)

print('PODSUMOWANIE WG DEPARTMENT:')
print(summary)

## <span style="color:#0f766e; font-weight:700;">Przykład 5: `merge`, `join`, `concat`</span>

Ta komórka pokazuje trzy różne sposoby łączenia danych.

In [ ]:
import pandas as pd

# Wczytujemy dwie tabele, które będziemy łączyć.
employees = pd.read_csv('dane_lekcja3/employees.csv')
departments = pd.read_csv('dane_lekcja3/departments.csv')

# merge() łączy tabele po wspólnym kluczu.
# Parametr on='department' mówi, że kluczem jest kolumna department po obu stronach.
# Parametr how='left' oznacza: zachowaj wszystkie rekordy z lewej tabeli (employees).
# Parametr indicator=True dodaje kolumnę _merge z informacją o dopasowaniu rekordów.
merged = employees.merge(departments, on='department', how='left', indicator=True)
print('MERGE:')
print(merged[['employee_id', 'department', 'director', '_merge']].head())
print()

# join() jest wygodny, gdy łączymy po indeksie.
# Najpierw ustawiamy w obu tabelach department jako indeks.
emp_idx = employees.set_index('department')
dep_idx = departments.set_index('department')

# Parametr how='left' działa analogicznie jak w merge.
# Parametr rsuffix='_dept' dodaje sufiks do kolumn konfliktujących nazwami po prawej stronie.
joined = emp_idx.join(dep_idx, how='left', rsuffix='_dept')
print('JOIN:')
print(joined[['employee_id', 'director', 'budget_k_pln']].head())
print()

# concat() skleja obiekty razem.
# Tutaj bierzemy dwa fragmenty tej samej tabeli.
part_a = employees.head(2)
part_b = employees.tail(2)

# Parametr axis=0 oznacza sklejanie pionowe, czyli dokładanie wierszy.
concatenated = pd.concat([part_a, part_b], axis=0)
print('CONCAT:')
print(concatenated[['employee_id', 'department']])

## <span style="color:#0f766e; font-weight:700;">Przykład 6: `melt`, `pivot`, `pivot_table`</span>

Ta komórka pokazuje zmianę kształtu danych: z układu szerokiego na długi i budowę tabeli przestawnej.

In [ ]:
import pandas as pd

# Wczytujemy dane w układzie szerokim (wide).
scores = pd.read_csv('dane_lekcja3/employee_scores_wide.csv')

# melt() zamienia wiele kolumn wyników na układ długi.
# Parametr id_vars='employee_id' wskazuje kolumnę identyfikującą rekord.
# Parametr var_name='quarter' tworzy nową kolumnę z dawnymi nazwami kolumn.
# Parametr value_name='score' tworzy kolumnę z wartościami.
scores_long = scores.melt(
    id_vars='employee_id',
    var_name='quarter',
    value_name='score'
)
print('MELT (wide -> long):')
print(scores_long.head())
print()

# Przygotowujemy małą, ale kompletną próbkę do demonstracji pivot().
# Bierzemy 3 identyfikatory, dla których istnieją wszystkie 4 kwartały.
example_ids = scores['employee_id'].head(3).tolist()
small = scores_long[scores_long['employee_id'].isin(example_ids)].copy()

# pivot() zamienia układ długi z powrotem na szeroki.
# Parametr index='employee_id' ustawia wiersze.
# Parametr columns='quarter' tworzy kolumny z nazw kwartałów.
# Parametr values='score' wskazuje, jakie wartości wypełniają komórki.
pivoted = small.pivot(index='employee_id', columns='quarter', values='score')
print('PIVOT (long -> wide, kompletna probka):')
print(pivoted)
print()

# Wczytujemy drugą tabelę do demonstracji pivot_table().
hours = pd.read_csv('dane_lekcja3/monthly_hours.csv')

# pivot_table() działa jak tabela przestawna z agregacją.
# Parametr index='month' ustawia wiersze tabeli wynikowej.
# Parametr values='billable_hours' wskazuje kolumnę do agregacji.
# Parametr aggfunc='mean' mówi, że liczymy średnią.
pivot_tbl = hours.pivot_table(
    index='month',
    values='billable_hours',
    aggfunc='mean'
)
print('PIVOT_TABLE (srednie billable_hours wg month):')
print(pivot_tbl)

## <span style="color:#0f766e; font-weight:700;">Przykład 7: `.str`, `pd.to_datetime()`, `.dt`</span>

Ta komórka pokazuje pracę z tekstem i datami na kolumnach `DataFrame`.

In [ ]:
import pandas as pd

# Wczytujemy dane pracowników.
df = pd.read_csv('dane_lekcja3/employees.csv')

# Operacje tekstowe przez accessor .str.
# str.lower() zamienia tekst na małe litery.
# str.strip() usuwa zbędne spacje z początku i końca tekstu.
df['first_name_clean'] = df['first_name'].str.lower().str.strip()
df['last_name_clean'] = df['last_name'].str.lower().str.strip()

# Łączymy dwie kolumny tekstowe w jedną nową kolumnę full_name.
df['full_name'] = df['first_name_clean'] + ' ' + df['last_name_clean']

# str.contains('a') sprawdza, czy w tekście występuje litera 'a'.
# Wynik to seria wartości True/False.
df['is_name_with_a'] = df['full_name'].str.contains('a')

print('OPERACJE TEKSTOWE:')
print(df[['first_name', 'last_name', 'full_name', 'is_name_with_a']].head())
print()

# pd.to_datetime() konwertuje tekst na typ daty.
# Parametr przekazujemy jako serię, którą chcemy przekonwertować.
df['hire_date'] = pd.to_datetime(df['hire_date'])

# Accessor .dt udostępnia operacje na dacie.
# dt.year wyciąga rok.
# dt.month wyciąga numer miesiąca.
# dt.day_name() zwraca nazwę dnia tygodnia.
df['hire_year'] = df['hire_date'].dt.year
df['hire_month'] = df['hire_date'].dt.month
df['hire_day_name'] = df['hire_date'].dt.day_name()

print('OPERACJE NA DATACH:')
print(df[['hire_date', 'hire_year', 'hire_month', 'hire_day_name']].head())

# <span style="color:#0f766e; font-weight:700;">3. Dane do ćwiczeń</span>

Pliki znajdują się w folderze `dane_lekcja3/`:

- `employees.csv` (700 wierszy)
- `departments.csv` (8 wierszy)
- `employee_scores_wide.csv` (500 wierszy)
- `monthly_hours.csv` (1400 wierszy)
- `README.md`

# <span style="color:#0f766e; font-weight:700;">4. Zadania</span>

## <span style="color:#0f766e; font-weight:700;">Zadanie 1</span>

Wczytaj `employees.csv` i wykonaj pełną szybką diagnostykę tabeli: `head`, `tail`, `sample`, `shape`, `info`, `dtypes`, `describe`.

Wymagane funkcje/parametry:
- `pd.read_csv()` - wczytuje plik CSV do `DataFrame`.
- `head()` - pokazuje pierwsze wiersze tabeli.
- `tail()` - pokazuje ostatnie wiersze tabeli.
- `sample()` - losuje kilka przykładowych rekordów.
- `shape` - podaje liczbę wierszy i kolumn.
- `info()` - pokazuje strukturę tabeli, typy i braki danych.
- `dtypes` - pokazuje typ każdej kolumny.
- `describe()` - liczy podstawowe statystyki opisowe.

Kryterium zaliczenia:
- zadanie wykonane zgodnie z poleceniem,
- wynik pokazany w notebooku.

Checkpoint:
- pokaż prowadzącemu wynik końcowy tej sekcji.

Dokumentacja:
- https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
- https://pandas.pydata.org/docs/reference/frame.html

In [1]:
import pandas as pd

df = pd.read_csv('dane_lekcja3/employees.csv')

print('HEAD:')
print(df.head())
print()

print('TAIL:')
print(df.tail())
print()

print('SAMPLE (3):')

print(df.sample(3, random_state=42))
print()

print('SHAPE:', df.shape)
print()

print('INFO:')
df.info()
print()

print('DTYPES:')
print(df.dtypes)
print()

print('DESCRIBE:')
print(df.describe(include='all').T.head(10))

HEAD:
   employee_id first_name  last_name department     city  age  salary_pln  \
0            1     Szymon  Zielinski      sales  Wroclaw   31    12928.65
1            2      Marta   Kowalski         hr   Krakow   25     9648.33
2            3        Iga  Kaczmarek         hr   Poznan   23    10907.36
3            4    Roksana      Mazur        ops  Wroclaw   55    10229.72
4            5     Celina  Kaczmarek  analytics   Poznan   57     8448.04

   bonus_pct  performance_score  projects_count  remote_days   hire_date  \
0      0.076               4.23               9            1  2021-02-09
1      0.068               3.28               8           13  2024-10-02
2      0.166               2.76               4           13  2020-05-17
3      0.011               3.06               8            0  2023-05-31
4      0.163               2.60               1            5  2024-05-26

   is_manager contract_type
0           0      Zlecenie
1           0           UoP
2           1           UoP
3           1           UoP
4           0           UoP

TAIL:
     employee_id first_name  last_name department      city  age  salary_pln  \
695          696     Alicja      Mazur         hr    Gdansk   55     9535.34
696          697     Szymon  Grabowska        ops  Warszawa   43    11872.27
697          698   Gabriela     Wojcik  analytics      Lodz   48    10737.17
698          699   Wiktoria     Wojcik   research    Poznan   35     9374.70
699          700   Gabriela      Nowak        ops      Lodz   45    10515.37

     bonus_pct  performance_score  projects_count  remote_days   hire_date  \
695      0.039               2.25               2            0  2018-10-17
696      0.164               4.39              10            3  2018-08-19
697      0.228               3.61               7            4  2018-08-20
698      0.194               3.39              11           19  2024-03-11
699      0.064               2.45               5           18  2022-07-16

     is_manager contract_type
695           0      Zlecenie
696           1           B2B
697           0           B2B
698           0           UoP
699           0           UoP

SAMPLE (3):
     employee_id first_name   last_name department    city  age  salary_pln  \
158          159     Tomasz    Krawczyk    product    Lodz   37    13087.14
500          501    Roksana  Piotrowski   research  Krakow   24     9176.85
396          397     Patryk      Wojcik         it  Lublin   24    13349.23

     bonus_pct  performance_score  projects_count  remote_days   hire_date  \
158      0.230               4.73               6           11  2024-04-05
500      0.046               2.26               9           16  2021-08-01
396      0.101               3.09               6            8  2019-01-18

     is_manager contract_type
158           0           B2B
500           0           UoP
396           1           UoP

SHAPE: (700, 14)

INFO:
<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        700 non-null    int64
 1   first_name         700 non-null    str
 2   last_name          700 non-null    str
 3   department         700 non-null    str
 4   city               700 non-null    str
 5   age                700 non-null    int64
 6   salary_pln         700 non-null    float64
 7   bonus_pct          700 non-null    float64
 8   performance_score  700 non-null    float64
 9   projects_count     700 non-null    int64
 10  remote_days        700 non-null    int64
 11  hire_date          700 non-null    str
 12  is_manager         700 non-null    int64
 13  contract_type      700 non-null    str
dtypes: float64(3), int64(5), str(6)
memory usage: 76.7 KB

DTYPES:
employee_id            int64
first_name               str
last_name                str
department               str
city                     str
age                    int64
salary_pln           float64
bonus_pct            float64
performance_score    float64
projects_count         int64
remote_days            int64
hire_date                str
is_manager             int64
contract_type            str
dtype: object

DESCRIBE:
                   count unique       top freq          mean         std  \
employee_id        700.0    NaN       NaN  NaN         350.5   202.21688
first_name           700     20    Tomasz   44           NaN         NaN
last_name            700     10    Wojcik   89           NaN         NaN
department           700      8  research  106           NaN         NaN
city                 700      8      Lodz  108           NaN         NaN
age                700.0    NaN       NaN  NaN     40.137143   11.067541
salary_pln         700.0    NaN       NaN  NaN  11459.368657  2318.97145
bonus_pct          700.0    NaN       NaN  NaN       0.12885    0.072209
performance_score  700.0    NaN       NaN  NaN      3.415414    0.876955
projects_count     700.0    NaN       NaN  NaN      6.164286    3.165919

                       min        25%        50%         75%       max
employee_id            1.0     175.75      350.5      525.25     700.0
first_name             NaN        NaN        NaN         NaN       NaN
last_name              NaN        NaN        NaN         NaN       NaN
department             NaN        NaN        NaN         NaN       NaN
city                   NaN        NaN        NaN         NaN       NaN
age                   22.0       30.0       40.0        50.0      58.0
salary_pln         4954.65  9789.1425  11469.375  12988.9975  20476.39
bonus_pct              0.0    0.06575     0.1315        0.19      0.25
performance_score      2.0       2.59       3.38        4.16      4.99
projects_count         1.0       3.75        6.0         9.0      11.0

## <span style="color:#0f766e; font-weight:700;">Zadanie 2</span>

Wybierz tylko kolumny `department`, `city`, `salary_pln`, `performance_score`. Następnie pokaż pracowników z pensją powyżej 12000 PLN.

Wymagane funkcje/parametry:
- wybór kolumn `df[[...]]` - tworzy nowy `DataFrame` z wybranymi kolumnami.
- `loc[]` - pozwala filtrować i wybierać konkretne kolumny jednocześnie.
- filtrowanie logiczne - zostawia tylko rekordy spełniające warunek.
- `query()` (opcjonalnie) - pozwala zapisać filtr w czytelnej formie tekstowej.

Kryterium zaliczenia:
- zadanie wykonane zgodnie z poleceniem,
- wynik pokazany w notebooku.

Checkpoint:
- pokaż prowadzącemu wynik końcowy tej sekcji.

Dokumentacja:
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html

In [6]:
df = pd.read_csv('dane_lekcja3/employees.csv')

kolumny = df[['department','city','salary_pln','performance_score']]

pracownicy = df[['first_name','last_name']]

pensja = pracownicy[df['salary_pln']>12000]

print(pensja)

    first_name  last_name
0       Szymon  Zielinski
5     Gabriela  Kaczmarek
6       Daniel  Zielinski
7          Iga      Mazur
10    Gabriela     Wojcik
..         ...        ...
688     Tomasz     Wojcik
689        Jan     Wojcik
690   Karolina  Kaczmarek
691    Nikodem     Wojcik
694     Alicja      Mazur

[281 rows x 2 columns]

## <span style="color:#0f766e; font-weight:700;">Zadanie 3</span>

Użyj `loc` i `iloc`, aby pokazać różnicę między wyborem po etykietach i po pozycjach. Wyświetl 5 wybranych rekordów obiema metodami.

Wymagane funkcje/parametry:
- `loc[]` - wybiera dane po nazwach etykiet (indeks, kolumny).
- `iloc[]` - wybiera dane po numerach pozycji.

Kryterium zaliczenia:
- zadanie wykonane zgodnie z poleceniem,
- wynik pokazany w notebooku.

Checkpoint:
- pokaż prowadzącemu wynik końcowy tej sekcji.

Dokumentacja:
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html

In [11]:
df = pd.read_csv('dane_lekcja3/employees.csv')

print(df.loc[0:4, ['first_name','last_name','department'] ])
print("\n")
print(df.iloc[0:5, 1:4 ])

  first_name  last_name department
0     Szymon  Zielinski      sales
1      Marta   Kowalski         hr
2        Iga  Kaczmarek         hr
3    Roksana      Mazur        ops
4     Celina  Kaczmarek  analytics


  first_name  last_name department
0     Szymon  Zielinski      sales
1      Marta   Kowalski         hr
2        Iga  Kaczmarek         hr
3    Roksana      Mazur        ops
4     Celina  Kaczmarek  analytics

## <span style="color:#0f766e; font-weight:700;">Zadanie 4</span>

Przekształć tabelę: zmień nazwę kolumny `salary_pln` na `salary`, dodaj kolumnę `annual_salary`, a następnie posortuj dane malejąco po `annual_salary`.

Wymagane funkcje/parametry:
- `rename()` - zmienia nazwę kolumny.
- `assign()` albo przypisanie kolumny - dodaje nową kolumnę do tabeli.
- `sort_values()` - sortuje rekordy według wartości w kolumnie.

Kryterium zaliczenia:
- zadanie wykonane zgodnie z poleceniem,
- wynik pokazany w notebooku.

Checkpoint:
- pokaż prowadzącemu wynik końcowy tej sekcji.

Dokumentacja:
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.assign.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html

In [12]:
df = pd.read_csv('dane_lekcja3/employees.csv')

df = df.rename(columns={'salary_pln':'salary'})
df = df.assign(
    annual_salary=df['salary'] * 12
)

sorted_df = df.sort_values('annual_salary', ascending=False)
sorted_df

,employee_id,first_name,last_name,department,city,age,salary,bonus_pct,performance_score,projects_count,remote_days,hire_date,is_manager,contract_type,annual_salary
646,647,Bartek,Zielinski,product,Warszawa,49,20476.39,0.204,4.98,2,1,2019-08-11,0,UoP,245716.68
263,264,Alicja,Nowak,it,Krakow,56,19185.99,0.040,2.86,2,7,2023-08-08,0,B2B,230231.88
191,192,Gabriela,Kaczmarek,it,Lodz,58,18163.82,0.180,3.14,6,20,2024-06-03,0,B2B,217965.84
630,631,Wiktoria,Kowalski,it,Lodz,53,17368.10,0.005,3.08,1,9,2018-07-11,1,B2B,208417.20
367,368,Jan,Wisniewski,it,Wroclaw,42,16798.54,0.031,3.41,1,5,2021-01-15,0,B2B,201582.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,540,Ewa,Grabowska,research,Krakow,31,6394.22,0.234,2.02,7,12,2022-07-17,0,UoP,76730.64
521,522,Karolina,Krawczyk,analytics,Warszawa,34,6092.28,0.034,2.19,1,17,2021-05-18,0,Zlecenie,73107.36
431,432,Alicja,Krawczyk,analytics,Szczecin,22,5855.24,0.199,4.86,4,18,2019-07-10,0,B2B,70262.88
178,179,Ewa,Mazur,hr,Lodz,54,5647.16,0.103,4.32,9,7,2022-03-22,0,UoP,67765.92
14,15,Alicja,Wojcik,research,Wroclaw,47,4954.65,0.218,2.46,4,9,2024-10-31,0,B2B,59455.80

## <span style="color:#0f766e; font-weight:700;">Zadanie 5</span>

Ustaw `employee_id` jako indeks, pokaż kilka rekordów, a potem przywróć zwykły indeks.

Wymagane funkcje/parametry:
- `set_index()` - ustawia wskazaną kolumnę jako indeks tabeli.
- `reset_index()` - przywraca zwykły indeks liczbowy.

Kryterium zaliczenia:
- zadanie wykonane zgodnie z poleceniem,
- wynik pokazany w notebooku.

Checkpoint:
- pokaż prowadzącemu wynik końcowy tej sekcji.

Dokumentacja:
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html

In [15]:
df = pd.read_csv('dane_lekcja3/employees.csv')

zindeksowane = sorted_df.set_index('employee_id')
print(zindeksowane.head(5))

print("/n")

revert = zindeksowane.reset_index()
print(revert.head(5))

            first_name   last_name department      city  age    salary  \
employee_id
647             Bartek   Zielinski    product  Warszawa   49  20476.39
264             Alicja       Nowak         it    Krakow   56  19185.99
192           Gabriela   Kaczmarek         it      Lodz   58  18163.82
631           Wiktoria    Kowalski         it      Lodz   53  17368.10
368                Jan  Wisniewski         it   Wroclaw   42  16798.54

             bonus_pct  performance_score  projects_count  remote_days  \
employee_id
647              0.204               4.98               2            1
264              0.040               2.86               2            7
192              0.180               3.14               6           20
631              0.005               3.08               1            9
368              0.031               3.41               1            5

              hire_date  is_manager contract_type  annual_salary
employee_id
647          2019-08-11           0           UoP      245716.68
264          2023-08-08           0           B2B      230231.88
192          2024-06-03           0           B2B      217965.84
631          2018-07-11           1           B2B      208417.20
368          2021-01-15           0           B2B      201582.48
/n
   employee_id first_name   last_name department      city  age    salary  \
0          647     Bartek   Zielinski    product  Warszawa   49  20476.39
1          264     Alicja       Nowak         it    Krakow   56  19185.99
2          192   Gabriela   Kaczmarek         it      Lodz   58  18163.82
3          631   Wiktoria    Kowalski         it      Lodz   53  17368.10
4          368        Jan  Wisniewski         it   Wroclaw   42  16798.54

   bonus_pct  performance_score  projects_count  remote_days   hire_date  \
0      0.204               4.98               2            1  2019-08-11
1      0.040               2.86               2            7  2023-08-08
2      0.180               3.14               6           20  2024-06-03
3      0.005               3.08               1            9  2018-07-11
4      0.031               3.41               1            5  2021-01-15

   is_manager contract_type  annual_salary
0           0           UoP      245716.68
1           0           B2B      230231.88
2           0           B2B      217965.84
3           1           B2B      208417.20
4           0           B2B      201582.48

## <span style="color:#0f766e; font-weight:700;">Zadanie 6</span>

Policz liczebności działów i miast. Następnie oblicz średnią pensję i medianę pensji w podziale na `department`.

Wymagane funkcje/parametry:
- `value_counts()` - liczy częstość występowania wartości.
- `groupby()` - dzieli dane na grupy według kolumny `department`.
- `agg()` - pozwala policzyć kilka agregacji jednocześnie.
- `mean()` - liczy średnią pensję.
- `median()` - liczy medianę pensji.

Kryterium zaliczenia:
- zadanie wykonane zgodnie z poleceniem,
- wynik pokazany w notebooku.

Checkpoint:
- pokaż prowadzącemu wynik końcowy tej sekcji.

Dokumentacja:
- https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html

In [20]:
df = pd.read_csv('dane_lekcja3/employees.csv')

print(df['department'].value_counts())
print('\n')
print(df['city'].value_counts())

podsumowanie = df.groupby('department').agg(
    
    salary_mean=('salary_pln', 'mean'),
    salary_median=('salary_pln', 'median'),
)

podsumowanie = podsumowanie.sort_values('salary_mean', ascending=False)

podsumowanie

department
research     106
it            96
ops           93
finance       88
hr            83
analytics     79
sales         78
product       77
Name: count, dtype: int64


city
Lodz        108
Wroclaw      97
Szczecin     92
Krakow       84
Poznan       84
Lublin       83
Warszawa     77
Gdansk       75
Name: count, dtype: int64

             salary_mean  salary_median
department
it          14097.585625      14098.655
product     13024.912338      12973.520
finance     12623.753864      12408.155
ops         11448.981290      11375.020
hr          10956.575422      11058.570
sales       10480.207051      10439.585
research     9812.851226       9562.405
analytics    9146.985443       9131.860

## <span style="color:#0f766e; font-weight:700;">Zadanie 7</span>

Wczytaj `departments.csv` i połącz go z `employees.csv`. Sprawdź, czy każdy pracownik dostał poprawne dane działu.

Wymagane funkcje/parametry:
- `pd.read_csv()` - wczytuje dane z pliku CSV.
- `merge()` - łączy tabele po wspólnym kluczu.
- parametr `how` - określa typ złączenia (`left`, `inner`, `right`, `outer`).
- parametr `indicator=True` - dodaje kolumnę pokazującą źródło dopasowania rekordów.

Kryterium zaliczenia:
- zadanie wykonane zgodnie z poleceniem,
- wynik pokazany w notebooku.

Checkpoint:
- pokaż prowadzącemu wynik końcowy tej sekcji.

Dokumentacja:
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html

In [34]:
pracownicy = pd.read_csv('dane_lekcja3/employees.csv')
departamenty = pd.read_csv('dane_lekcja3/departments.csv')

zlaczone = pracownicy.merge(departamenty, on='department', how='left', indicator=True)

print(f"{pracownicy}")
print(f"\n{departamenty}")
print(f"\n{zlaczone}")

     employee_id first_name  last_name department      city  age  salary_pln  \
0              1     Szymon  Zielinski      sales   Wroclaw   31    12928.65
1              2      Marta   Kowalski         hr    Krakow   25     9648.33
2              3        Iga  Kaczmarek         hr    Poznan   23    10907.36
3              4    Roksana      Mazur        ops   Wroclaw   55    10229.72
4              5     Celina  Kaczmarek  analytics    Poznan   57     8448.04
..           ...        ...        ...        ...       ...  ...         ...
695          696     Alicja      Mazur         hr    Gdansk   55     9535.34
696          697     Szymon  Grabowska        ops  Warszawa   43    11872.27
697          698   Gabriela     Wojcik  analytics      Lodz   48    10737.17
698          699   Wiktoria     Wojcik   research    Poznan   35     9374.70
699          700   Gabriela      Nowak        ops      Lodz   45    10515.37

     bonus_pct  performance_score  projects_count  remote_days   hire_date  \
0        0.076               4.23               9            1  2021-02-09
1        0.068               3.28               8           13  2024-10-02
2        0.166               2.76               4           13  2020-05-17
3        0.011               3.06               8            0  2023-05-31
4        0.163               2.60               1            5  2024-05-26
..         ...                ...             ...          ...         ...
695      0.039               2.25               2            0  2018-10-17
696      0.164               4.39              10            3  2018-08-19
697      0.228               3.61               7            4  2018-08-20
698      0.194               3.39              11           19  2024-03-11
699      0.064               2.45               5           18  2022-07-16

     is_manager contract_type
0             0      Zlecenie
1             0           UoP
2             1           UoP
3             1           UoP
4             0           UoP
..          ...           ...
695           0      Zlecenie
696           1           B2B
697           0           B2B
698           0           UoP
699           0           UoP

[700 rows x 14 columns]

  department    director  budget_k_pln  floor
0  analytics  Dyrektor_1           958      8
1   research  Dyrektor_2           613     10
2      sales  Dyrektor_3           982      3
3         hr  Dyrektor_4          1962      4
4        ops  Dyrektor_5          2222      3
5    finance  Dyrektor_6           687      9
6    product  Dyrektor_7           971     10
7         it  Dyrektor_8           631      4

     employee_id first_name  last_name department      city  age  salary_pln  \
0              1     Szymon  Zielinski      sales   Wroclaw   31    12928.65
1              2      Marta   Kowalski         hr    Krakow   25     9648.33
2              3        Iga  Kaczmarek         hr    Poznan   23    10907.36
3              4    Roksana      Mazur        ops   Wroclaw   55    10229.72
4              5     Celina  Kaczmarek  analytics    Poznan   57     8448.04
..           ...        ...        ...        ...       ...  ...         ...
695          696     Alicja      Mazur         hr    Gdansk   55     9535.34
696          697     Szymon  Grabowska        ops  Warszawa   43    11872.27
697          698   Gabriela     Wojcik  analytics      Lodz   48    10737.17
698          699   Wiktoria     Wojcik   research    Poznan   35     9374.70
699          700   Gabriela      Nowak        ops      Lodz   45    10515.37

     bonus_pct  performance_score  projects_count  remote_days   hire_date  \
0        0.076               4.23               9            1  2021-02-09
1        0.068               3.28               8           13  2024-10-02
2        0.166               2.76               4           13  2020-05-17
3        0.011               3.06               8            0  2023-05-31
4        0.163               2.60               1            5  2024-05-26
..         ...                ...             ...          ...         ...
695      0.039               2.25               2            0  2018-10-17
696      0.164               4.39              10            3  2018-08-19
697      0.228               3.61               7            4  2018-08-20
698      0.194               3.39              11           19  2024-03-11
699      0.064               2.45               5           18  2022-07-16

     is_manager contract_type    director  budget_k_pln  floor _merge
0             0      Zlecenie  Dyrektor_3           982      3   both
1             0           UoP  Dyrektor_4          1962      4   both
2             1           UoP  Dyrektor_4          1962      4   both
3             1           UoP  Dyrektor_5          2222      3   both
4             0           UoP  Dyrektor_1           958      8   both
..          ...           ...         ...           ...    ...    ...
695           0      Zlecenie  Dyrektor_4          1962      4   both
696           1           B2B  Dyrektor_5          2222      3   both
697           0           B2B  Dyrektor_1           958      8   both
698           0           UoP  Dyrektor_2           613     10   both
699           0           UoP  Dyrektor_5          2222      3   both

[700 rows x 18 columns]

## <span style="color:#0f766e; font-weight:700;">Zadanie 8</span>

Wczytaj `employee_scores_wide.csv`, a następnie zamień układ szeroki na długi (`wide` -> `long`).

Wymagane funkcje/parametry:
- `pd.read_csv()` - wczytuje dane z pliku CSV.
- `melt()` - zamienia wiele kolumn na układ długi z jedną kolumną nazw i jedną kolumną wartości.
- parametr `id_vars` - wskazuje kolumny identyfikujące rekord.
- parametr `var_name` - nadaje nazwę kolumnie z dawnymi nazwami kolumn.
- parametr `value_name` - nadaje nazwę kolumnie z wartościami.

Kryterium zaliczenia:
- zadanie wykonane zgodnie z poleceniem,
- wynik pokazany w notebooku.

Checkpoint:
- pokaż prowadzącemu wynik końcowy tej sekcji.

Dokumentacja:
- https://pandas.pydata.org/docs/reference/api/pandas.melt.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.melt.html

In [38]:
wyniki_szerokie = pd.read_csv('dane_lekcja3/employee_scores_wide.csv')

print(wyniki_szerokie.head())

wyniki_dlugie = wyniki_szerokie.melt(
    id_vars='employee_id',
    var_name='quarter',
    value_name='score'
)

print(wyniki_dlugie.head())

   employee_id  score_q1  score_q2  score_q3  score_q4
0            1      56.9      96.9      66.7      86.6
1            2      73.6      61.1      74.2      97.1
2            3      73.8      51.7      53.9      99.3
3            4      86.8      94.2      88.1      79.5
4            5      62.0      50.7      99.0      80.2
   employee_id   quarter  score
0            1  score_q1   56.9
1            2  score_q1   73.6
2            3  score_q1   73.8
3            4  score_q1   86.8
4            5  score_q1   62.0

## <span style="color:#0f766e; font-weight:700;">Zadanie 9 - dodatkowe</span>

Na podstawie `monthly_hours.csv` zbuduj tabelę przestawną pokazującą średnie `billable_hours` w podziale na `month` i `employee_id` albo `department` (po wcześniejszym merge).

Wymagane funkcje/parametry:
- `pd.read_csv()` - wczytuje dane z pliku CSV.
- `merge()` - łączy tabelę godzin z inną tabelą, np. pracowników.
- `pivot_table()` - buduje tabelę przestawną z agregacją.
- parametr `index` - ustawia wiersze tabeli przestawnej.
- parametr `columns` - ustawia kolumny tabeli przestawnej.
- parametr `values` - wskazuje, którą zmienną agregować.
- parametr `aggfunc` - określa, jaką funkcję agregującą zastosować.

Kryterium zaliczenia:
- zadanie wykonane zgodnie z poleceniem,
- wynik pokazany w notebooku.

Checkpoint:
- pokaż prowadzącemu wynik końcowy tej sekcji.

Dokumentacja:
- https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html

In [56]:
employees = pd.read_csv('dane_lekcja3/employees.csv')
monthly_hours = pd.read_csv('dane_lekcja3/monthly_hours.csv')

merged = monthly_hours.merge(employees, on='employee_id', how='left')

merged = merged.sort_values('employee_id', ascending=True)

pivot_tbl = merged.pivot_table(
    index='month',
    columns ='department',
    values='billable_hours',
    aggfunc='mean'

    
)

pivot_tbl

department,analytics,finance,hr,it,ops,product,research,sales
month,,,,,,,,
2025-01,110.526087,114.587500,107.706452,104.754545,106.331034,114.586667,112.547727,112.285185
2025-02,111.493548,105.240625,114.123333,103.683871,104.443750,113.490625,105.123333,107.030435
2025-03,115.868966,105.944444,117.286207,98.984375,110.515909,120.025000,103.158824,113.810000
2025-04,108.332143,105.656667,109.105000,107.044737,108.417391,118.682609,118.525641,110.013793
2025-05,109.336364,115.745161,117.645833,107.748000,117.687500,112.587500,117.994444,91.455556
2025-06,109.317241,103.719231,110.696000,107.688889,106.954054,98.454545,111.945833,102.862162

## <span style="color:#0f766e; font-weight:700;">Zadanie 10 - dodatkowe</span>

Wykorzystaj accessor `.str`: zamień `first_name` i `last_name` na małe litery, usuń spacje (jeśli są), a potem zbuduj kolumnę `full_name`.

Wymagane funkcje/parametry:
- `.str.lower()` - zamienia tekst na małe litery.
- `.str.strip()` - usuwa zbędne spacje z początku i końca tekstu.
- operacje na kolumnach tekstowych - pozwalają łączyć tekst z kilku kolumn w jedną nową kolumnę.

Kryterium zaliczenia:
- zadanie wykonane zgodnie z poleceniem,
- wynik pokazany w notebooku.

Checkpoint:
- pokaż prowadzącemu wynik końcowy tej sekcji.

Dokumentacja:
- https://pandas.pydata.org/docs/reference/api/pandas.Series.str.lower.html
- https://pandas.pydata.org/docs/reference/api/pandas.Series.str.strip.html

In [57]:
# tutaj dodaj swój kod
df = pd.read_csv('dane_lekcja3/employees.csv')

df['first_name'] = df['first_name'].str.lower().str.strip()
df['last_name'] = df['last_name'].str.lower().str.strip()

df['full_name'] = df['first_name'] + ' ' + df['last_name']
df

,employee_id,first_name,last_name,department,city,age,salary_pln,bonus_pct,performance_score,projects_count,remote_days,hire_date,is_manager,contract_type,full_name
0,1,szymon,zielinski,sales,Wroclaw,31,12928.65,0.076,4.23,9,1,2021-02-09,0,Zlecenie,szymon zielinski
1,2,marta,kowalski,hr,Krakow,25,9648.33,0.068,3.28,8,13,2024-10-02,0,UoP,marta kowalski
2,3,iga,kaczmarek,hr,Poznan,23,10907.36,0.166,2.76,4,13,2020-05-17,1,UoP,iga kaczmarek
3,4,roksana,mazur,ops,Wroclaw,55,10229.72,0.011,3.06,8,0,2023-05-31,1,UoP,roksana mazur
4,5,celina,kaczmarek,analytics,Poznan,57,8448.04,0.163,2.60,1,5,2024-05-26,0,UoP,celina kaczmarek
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,696,alicja,mazur,hr,Gdansk,55,9535.34,0.039,2.25,2,0,2018-10-17,0,Zlecenie,alicja mazur
696,697,szymon,grabowska,ops,Warszawa,43,11872.27,0.164,4.39,10,3,2018-08-19,1,B2B,szymon grabowska
697,698,gabriela,wojcik,analytics,Lodz,48,10737.17,0.228,3.61,7,4,2018-08-20,0,B2B,gabriela wojcik
698,699,wiktoria,wojcik,research,Poznan,35,9374.70,0.194,3.39,11,19,2024-03-11,0,UoP,wiktoria wojcik
699,700,gabriela,nowak,ops,Lodz,45,10515.37,0.064,2.45,5,18,2022-07-16,0,UoP,gabriela nowak

## <span style="color:#0f766e; font-weight:700;">Zadanie 11 - dodatkowe</span>

Wykorzystaj accessor `.dt`: zamień `hire_date` na typ daty, a potem wyciągnij rok zatrudnienia, miesiąc i nazwę dnia tygodnia.

Wymagane funkcje/parametry:
- `pd.to_datetime()` - konwertuje tekst na prawdziwy typ daty.
- `.dt.year` - wyciąga rok z daty.
- `.dt.month` - wyciąga numer miesiąca.
- `.dt.day_name()` - zwraca nazwę dnia tygodnia.

Kryterium zaliczenia:
- zadanie wykonane zgodnie z poleceniem,
- wynik pokazany w notebooku.

Checkpoint:
- pokaż prowadzącemu wynik końcowy tej sekcji.

Dokumentacja:
- https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html
- https://pandas.pydata.org/docs/reference/series.html#datetimelike-properties

In [58]:
# tutaj dodaj swój kod
df = pd.read_csv('dane_lekcja3/employees.csv')

df['hire_date'] = pd.to_datetime(df['hire_date'])

df['hire_year'] = df['hire_date'].dt.year
df['hire_month'] = df['hire_date'].dt.month
df['hire_day_name'] = df['hire_date'].dt.day_name()

print(df[['hire_date', 'hire_year', 'hire_month', 'hire_day_name']].head())

   hire_date  hire_year  hire_month hire_day_name
0 2021-02-09       2021           2       Tuesday
1 2024-10-02       2024          10     Wednesday
2 2020-05-17       2020           5        Sunday
3 2023-05-31       2023           5     Wednesday
4 2024-05-26       2024           5        Sunday

## <span style="color:#0f766e; font-weight:700;">Zadanie 12 - dodatkowe</span>

Przygotuj mini-podsumowanie `DataFrame`: jedna tabela agregacji + jedna tabela przestawna + 3 krótkie wnioski o danych pracowników.

Wymagane funkcje/parametry:
- `groupby()` - dzieli dane na grupy do dalszej agregacji.
- `agg()` - pozwala policzyć kilka miar w jednym kroku.
- `pivot_table()` - buduje tabelę przestawną do porównań.
- `sort_values()` - porządkuje wynik, np. od najwyższej wartości.
- `describe()` (opcjonalnie) - daje szybki statystyczny podgląd danych.

Kryterium zaliczenia:
- zadanie wykonane zgodnie z poleceniem,
- wynik pokazany w notebooku.

Checkpoint:
- pokaż prowadzącemu wynik końcowy tej sekcji.

Dokumentacja:
- https://pandas.pydata.org/docs/reference/frame.html

In [ ]:
# tutaj dodaj swój kod

## <span style="color:#0f766e; font-weight:700;">Najczęstsze błędy</span>

- mylenie `loc` i `iloc`,
- filtrowanie bez nawiasów przy wielu warunkach,
- nadpisywanie `DataFrame` bez kontroli, co zostało zmienione,
- używanie `merge()` bez sprawdzenia kluczy,
- zapominanie, że `.str` działa na tekście, a `.dt` na datach,
- próba użycia `pivot_table()` bez jasnego określenia `index` i `values`.